### ISSUE TITLE
Can it support multiple surfaces? (other than nauvis)

### ISSUE THREAD

**Issue by marimelon** [Palats/mapshot#14]
Can it  support mods that use multiple surfaces, such as [SpaceExploration](https://mods.factorio.com/mod/space-exploration)?

**Comment by Palats** [comment]
I'm not too familiar on how Factorio manages the difference surfaces in details, but that should be largely doable I imagine. Currently, the mod [only generates for nauvis](https://github.com/Palats/mapshot/blob/0.0.13.1/mod/control.lua#L68) indeed. The [take_screenshot](https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.take_screenshot) calls allow to specify the surface to render, so it should be possible to do a render per surface. As far as I can tell, it is also possible [to automatically list surface](https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.surfaces).

Some metadata would be needed in `mapshot.json` files but that would be trivial. Some thoughts would be needed for exact UI, but the UI library used (leaflet) has support for multiple layers, so something should be doable (it would be a different base layers, which is different from overlays, but still).

[to be clear - I have no immediate plan to write this feature myself for now though]

**Comment by drdozer** [comment]
```
/c for _, s in pairs(game.surfaces) do game.take_screenshot{surface = s, daytime = 1.0, path = s.name .. ".png" } end
```

This worked as expected after a bit of coaching from discord. I'll take a look at the mod code and see if it is beyond my noob lua skills to fix.

**Comment by drdozer** [comment]
If you are on discord we could have a conversation. Otherwise, I'm looking at control.lua. There are a few things to be done I think.

1. Decompose `mapshot` into two functions, one that deals with 'all' the data, and one that deals with a particular surface
2. Modify `gen_layer` to take the surface and use it in the `take_screenshot` call
3. Put the layer name into file names

The simplest version of this would simply generate a uniquely named mapshot instance per layer per game. The more complex version would bundle up the layers for a single game into a flipbook of maps.

**Comment by Palats** [comment]
Ok, I started digging a bit in the code to remember the details, one thing led to another and now there is support for other surfaces in https://github.com/Palats/mapshot/tree/surfaces ( https://github.com/Palats/mapshot/commit/202364c880f807a42722c466dfeea88f653de411 ).

This is not in the main branch for now as I don't have anything to test it with - would you have by any chance a modded save with non default surfaces that you can give me for me to test?

**Comment by drdozer** [comment]
Also, is there an 'all' option?

**Comment by Palats** [comment]
For sharing the save - any file sharing thing like google drive, dropbox or microsoft onedrive would do the trick. If you prefer to not have a public link, you can send it to my mail (I've updated my github profile with it) - though in that case, please indicate whether it is fine or not to share screenshot of that save.

For the `all` option - yeah, that would make sense. I might change the final approach a tiny bit, which will make it more natural to have a `all` option.

**Comment by Palats** [comment]
Actually, with mod https://mods.factorio.com/mod/ParallelWorlds I can easily do some basic testing of multi-surfaces (without having to do a run with SpaceExploration that is :) .

**Comment by drdozer** [comment]
Try this one:

https://drive.google.com/file/d/1PMYjI8orR1edLyavYDr6gJcPYYZGBj74/view?usp=sharing

Feel free to share anything about or from this save. Use it for screenshots for your mod for all I care. It should have several surfaces, each with something there to look at. The nauvis world also has a range of scales that seems to not work super well with the default map rendering settings - at some zooms it appears a bit too pixelated or blurry. I've not figured out exactly what setting tweaks will fix that though.

**Comment by Palats** [comment]
Ok, so release 0.0.14 which I just uploaded should now render all surfaces by default and allow to switch between them in the viewer.

There might be some corner cases where some of the surfaces do not render - when I tried on the save provided in https://github.com/Palats/mapshot/issues/14#issuecomment-945119937 (which was very useful, thanks), some screenshots do not render it seems. I think that's because I do not have all the necessary mods installed, though I'm not 100% sure - there might be some way the surfaces are used in the mods that I do not understand.
