### ISSUE TITLE
Viewer is trying to incorrectly load mapshot.json

### ISSUE THREAD

**Issue by IeuanK** [Palats/mapshot#56]
I have a habit of keeping an archive of my Mapshots inside a directory. This directory structure is `Factorio/<timestamp>/`.  
I just copy the entire mapshot output to the directory with the current timestamp (i.e. `20241112_1832`), and that worked perfectly up until about a week ago (presumably the most recent update).  

Before, it was correctly loading `Factorio/<timestamp>/<map_id>/mapshot.json`, now it tries to load `Factorio/<timestamp>/mapshot.json`, which does not exist.  
As an example of the actual structure, before it was loading `/Factorio/20241103_0217/d-4c0183c2/mapshot.json`, now it's trying to load `/Factorio/20241104_2359/mapshot.json`.  

Apparently something has changed in the viewer.js that makes it no longer properly account for the map ID, which results in broken maps.   

I've temporarily uploaded an older and a newer map to the following URLs:

Working: https://spotlesscopper.nl/factorio/
Not working: https://spotlesscopper.nl/factorio2/

I think the issue is the config value `encoded_path`, which is empty. It appears that the viewer.js now uses `encoded_path` instead of `path`, and it being empty leads to it not working.

**Comment by Palats** [comment]
Indeed that's likely because of a [recent change fixing encoding problems](https://github.com/Palats/mapshot/commit/fba2cbc7751757c38d65be8ac3bd72aed9ef9210), sorry about that.

How are you serving your maps - are you using simple static serving? I think I forgot to test this case when I did this change, so that's quite possible I missed something. Good catch on the `encode_path` vs `path`, that is very likely the issue; I think specifically I forgot to update [this part](https://github.com/Palats/mapshot/blob/23954a41d47282822aad0311151fc9a795b23fe3/mod/control.lua#L115).

As far as I have tested, for the already generated files, as a work around, you can edit the `index.html` in the generated content and replace `"path"` with `"encoded_path"` (within the `MAPSHOT_CONFIG` part).

I need to see to fix it - there is no URL encoding available in Lua, but I might be able to do without it.

**Comment by IeuanK** [comment]
I am indeed serving statically. The two links in my issue are Apache, but the same happens with Nginx.  
I use the mapshot command in-game (so not CLI) to generate the map, then copy the contents to the webroot.

Changing `path` to `encoded_path` does indeed fix it for a generated map!

**Comment by Palats** [comment]
There, version 0.0.25 should have the fix. It will not fix the existing mapshot unfortunately - they need to be fixed manually.

**Comment by IeuanK** [comment]
That fixed it, thank you for the quick update!
